/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.sistemalojaroupas.view;

/**
 *
 * @author lukas
 */
public class New_Sale extends javax.swing.JFrame {

    /**
     * Creates new form testeVENDAS
     */
    public New_Sale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_cancellation = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_price = new javax.swing.JTextField();
        btn_searchCPF = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_product = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_mark = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_color = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_size = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_CPF = new javax.swing.JFormattedTextField();
        txt_cod = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_SalesTotal = new javax.swing.JTextField();
        btn_searchCod = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_ShoppingCart = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txt_amount = new javax.swing.JTextField();
        radioBtn_credit = new javax.swing.JRadioButton();
        radioBtn_money = new javax.swing.JRadioButton();
        radioBtn_debit = new javax.swing.JRadioButton();
        btn_addToCart = new javax.swing.JButton();
        btn_payment = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nova Venda");
        setMaximumSize(new java.awt.Dimension(1260, 730));
        setMinimumSize(new java.awt.Dimension(1260, 730));
        setPreferredSize(new java.awt.Dimension(1260, 730));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nome :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 60, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 176, 240));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Carrinho de Compras");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 740, 40));

        btn_cancellation.setBackground(new java.awt.Color(192, 0, 0));
        btn_cancellation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cancellation.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancellation.setText("Cancelar Venda");
        btn_cancellation.setBorderPainted(false);
        jPanel1.add(btn_cancellation, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 590, 220, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CPF :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 60, 30));

        txt_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_name.setText("Lucas de Almeida Sarmento");
        txt_name.setBorder(null);
        jPanel1.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 280, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 176, 240));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Dados do Cliente");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 410, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Código :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 70, 30));

        txt_price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_price.setText("R$ 124,99");
        txt_price.setBorder(null);
        jPanel1.add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 120, 30));

        btn_searchCPF.setBackground(new java.awt.Color(108, 81, 233));
        btn_searchCPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_searchCPF.setForeground(new java.awt.Color(255, 255, 255));
        btn_searchCPF.setText("Pesquisar");
        btn_searchCPF.setBorderPainted(false);
        jPanel1.add(btn_searchCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 150, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Produto :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 80, 30));

        txt_product.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_product.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_product.setText("Camisa gola V");
        txt_product.setBorder(null);
        jPanel1.add(txt_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 280, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Marca :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 70, 30));

        txt_mark.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_mark.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_mark.setText("Rauph Lauren");
        txt_mark.setBorder(null);
        jPanel1.add(txt_mark, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 280, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cor :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 50, 30));

        txt_color.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_color.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_color.setText("Vermelho escuro");
        txt_color.setBorder(null);
        jPanel1.add(txt_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 160, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Preço :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 90, 30));

        txt_size.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_size.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_size.setText("G");
        txt_size.setBorder(null);
        jPanel1.add(txt_size, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 60, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Tamanho :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 90, 30));

        txt_CPF.setBorder(null);
        try {
            txt_CPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_CPF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_CPF.setText("123.456.789-10");
        txt_CPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txt_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 120, 30));

        txt_cod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_cod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cod.setText("123");
        txt_cod.setBorder(null);
        jPanel1.add(txt_cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 120, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Qtd. :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 80, 30));

        txt_SalesTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_SalesTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_SalesTotal.setText("R$ 249,98");
        txt_SalesTotal.setBorder(null);
        jPanel1.add(txt_SalesTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 590, 210, 50));

        btn_searchCod.setBackground(new java.awt.Color(108, 81, 233));
        btn_searchCod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_searchCod.setForeground(new java.awt.Color(255, 255, 255));
        btn_searchCod.setText("Pesquisar");
        btn_searchCod.setBorderPainted(false);
        jPanel1.add(btn_searchCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 150, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 176, 240));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Total da Venda");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 150, 40));

        table_ShoppingCart.setForeground(new java.awt.Color(0, 0, 51));
        table_ShoppingCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"123", "Camisa gola V", "Rauph Lauren", "G", "Vermelho escuro", "124,99", "2", "249,98"},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Produto", "Marca", "Tamanho", "Cor", "Preço", "Quantidade", "Subtotal"
            }
        ));
        table_ShoppingCart.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(table_ShoppingCart);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 720, 330));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 176, 240));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Dados do Produto");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 410, 40));

        txt_amount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_amount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_amount.setText("2");
        txt_amount.setBorder(null);
        jPanel1.add(txt_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 70, 30));

        radioBtn_credit.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radioBtn_credit);
        radioBtn_credit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioBtn_credit.setForeground(new java.awt.Color(0, 176, 240));
        radioBtn_credit.setText("   Crédito");
        radioBtn_credit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(radioBtn_credit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 540, 100, -1));

        radioBtn_money.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radioBtn_money);
        radioBtn_money.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioBtn_money.setForeground(new java.awt.Color(0, 176, 240));
        radioBtn_money.setText("   Dinheiro");
        radioBtn_money.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(radioBtn_money, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, 100, -1));

        radioBtn_debit.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radioBtn_debit);
        radioBtn_debit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioBtn_debit.setForeground(new java.awt.Color(0, 176, 240));
        radioBtn_debit.setText("   Débito");
        radioBtn_debit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(radioBtn_debit, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 540, 100, -1));

        btn_addToCart.setBackground(new java.awt.Color(108, 81, 233));
        btn_addToCart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_addToCart.setForeground(new java.awt.Color(255, 255, 255));
        btn_addToCart.setText("Adicionar ao Carrinho");
        btn_addToCart.setBorderPainted(false);
        jPanel1.add(btn_addToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 220, 50));

        btn_payment.setBackground(new java.awt.Color(0, 176, 80));
        btn_payment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_payment.setForeground(new java.awt.Color(255, 255, 255));
        btn_payment.setText("Pagamento");
        btn_payment.setBorderPainted(false);
        jPanel1.add(btn_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 590, 220, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background_VENDAS.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_Sale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_addToCart;
    private javax.swing.JButton btn_cancellation;
    private javax.swing.JButton btn_payment;
    private javax.swing.JButton btn_searchCPF;
    private javax.swing.JButton btn_searchCod;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioBtn_credit;
    private javax.swing.JRadioButton radioBtn_debit;
    private javax.swing.JRadioButton radioBtn_money;
    private javax.swing.JTable table_ShoppingCart;
    private javax.swing.JFormattedTextField txt_CPF;
    private javax.swing.JTextField txt_SalesTotal;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_cod;
    private javax.swing.JTextField txt_color;
    private javax.swing.JTextField txt_mark;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_product;
    private javax.swing.JTextField txt_size;
    // End of variables declaration//GEN-END:variables
}
