/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.sistemalojaroupas.view;

import br.sistemalojaroupas.model.dao.ClientDao;
import br.sistemalojaroupas.model.entities.Client;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Mariana
 */
public class Register_And_Edit_Customer extends javax.swing.JDialog {

    /**
     * Creates new form New_Customer
     */
    public Register_And_Edit_Customer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        jPanel1.setBackground(new Color(0, 0, 0, 0));
    }

    public void limpaCampos() {
        cEmail.setText("");
        cCPF.setText("");
        cCell.setText("");
        cName.setText("");
        cEmail.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cEmail = new javax.swing.JTextField();
        cName = new javax.swing.JTextField();
        cCPF = new javax.swing.JFormattedTextField();
        cCell = new javax.swing.JFormattedTextField();
        btn_Savec = new javax.swing.JLabel();
        btn_Cancelc = new javax.swing.JLabel();
        btn_Cleanc = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(59, 44, 150));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nome:");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, 30));

        jLabel2.setBackground(new java.awt.Color(59, 44, 150));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CPF:");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 30));

        jLabel3.setBackground(new java.awt.Color(59, 44, 150));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("E-mail:");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 80, 30));

        jLabel4.setBackground(new java.awt.Color(59, 44, 150));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Celular:");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 80, 30));

        cEmail.setBackground(new java.awt.Color(0, 0, 51));
        cEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cEmail.setForeground(new java.awt.Color(255, 255, 255));
        cEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(108, 81, 233)));
        jPanel1.add(cEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 329, 30));

        cName.setBackground(new java.awt.Color(0, 0, 51));
        cName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cName.setForeground(new java.awt.Color(255, 255, 255));
        cName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(108, 81, 233)));
        jPanel1.add(cName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 329, 30));

        cCPF.setBackground(new java.awt.Color(0, 0, 51));
        cCPF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(108, 81, 233)));
        cCPF.setForeground(new java.awt.Color(255, 255, 255));
        try {
            cCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cCPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(cCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 180, 30));

        cCell.setBackground(new java.awt.Color(0, 0, 51));
        cCell.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(108, 81, 233)));
        cCell.setForeground(new java.awt.Color(255, 255, 255));
        try {
            cCell.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cCell.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(cCell, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 180, 30));

        btn_Savec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_salvarClaro.png"))); // NOI18N
        btn_Savec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SavecMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SavecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SavecMouseExited(evt);
            }
        });
        jPanel1.add(btn_Savec, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        btn_Cancelc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_cancelarClaro.png"))); // NOI18N
        btn_Cancelc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CancelcMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CancelcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CancelcMouseExited(evt);
            }
        });
        jPanel1.add(btn_Cancelc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        btn_Cleanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_limparClaro.png"))); // NOI18N
        btn_Cleanc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CleancMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CleancMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CleancMouseExited(evt);
            }
        });
        jPanel1.add(btn_Cleanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CADASTRAR NOVO CLIENTE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tela_cadastro_dark.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CleancMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CleancMouseClicked
        limpaCampos();
    }//GEN-LAST:event_btn_CleancMouseClicked

    private void btn_CancelcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelcMouseClicked
        int op;
        op = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (op == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btn_CancelcMouseClicked

    private void btn_SavecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SavecMouseClicked
        Client client = new Client();
        
        client.setNome(cName.getText().toUpperCase());
        client.setCpf(cCPF.getText());
        client.setEmail(cEmail.getText());
        client.setCelular(cCell.getText());
        
        ClientDao.insert(client);
                
        JOptionPane.showMessageDialog(null, "Dados salvos com sucesso!", "Confirmação", JOptionPane.INFORMATION_MESSAGE);
        limpaCampos();
    }//GEN-LAST:event_btn_SavecMouseClicked

    private void btn_CancelcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelcMouseEntered
        btn_Cancelc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_cancelar.png")));
    }//GEN-LAST:event_btn_CancelcMouseEntered

    private void btn_CancelcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelcMouseExited
        btn_Cancelc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_cancelarClaro.png")));
    }//GEN-LAST:event_btn_CancelcMouseExited

    private void btn_SavecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SavecMouseEntered
        btn_Savec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_salvar.png")));
    }//GEN-LAST:event_btn_SavecMouseEntered

    private void btn_SavecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SavecMouseExited
        btn_Savec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_salvarClaro.png")));
    }//GEN-LAST:event_btn_SavecMouseExited

    private void btn_CleancMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CleancMouseEntered
        btn_Cleanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_limpar.png")));
    }//GEN-LAST:event_btn_CleancMouseEntered

    private void btn_CleancMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CleancMouseExited
        btn_Cleanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_limparClaro.png")));
    }//GEN-LAST:event_btn_CleancMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_And_Edit_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_And_Edit_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_And_Edit_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_And_Edit_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Register_And_Edit_Customer dialog = new Register_And_Edit_Customer(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Cancelc;
    private javax.swing.JLabel btn_Cleanc;
    private javax.swing.JLabel btn_Savec;
    private javax.swing.JFormattedTextField cCPF;
    private javax.swing.JFormattedTextField cCell;
    private javax.swing.JTextField cEmail;
    private javax.swing.JTextField cName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
