/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.sistemalojaroupas.view;

import br.sistemalojaroupas.model.dao.CategoryDao;
import br.sistemalojaroupas.model.dao.ColorDao;
import br.sistemalojaroupas.model.dao.ProductDao;
import br.sistemalojaroupas.model.entities.Category;
import br.sistemalojaroupas.model.entities.Product;
import br.sistemalojaroupas.view.util.ComboBoxRenderer;
import br.sistemalojaroupas.model.entities.Color;
import br.sistemalojaroupas.view.listeners.DataChangeListener;
import br.sistemalojaroupas.view.util.Utils;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author lukas
 */
public class Register_And_Edit_Products extends javax.swing.JDialog {
    
    private Product product;
    private List<DataChangeListener> listeners = new ArrayList<>();
    /**
     * Creates new form Register_Products
     */
    
    public Register_And_Edit_Products(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();   
        
        this.setBackground(new java.awt.Color(0,0,0,0));
        pnl_Background.setBackground(new java.awt.Color(0,0,0,0));
        
        Utils.updateComboBox(CategoryDao.findAll(), cbCategory);
        Utils.updateComboBox(ColorDao.findAll(), cbColor);
        
        setAllComboBoxRenderer();
    }
    
    public Register_And_Edit_Products(java.awt.Dialog owner, boolean modal, Product product) {
        super(owner, modal);
        initComponents();
        
        this.setBackground(new java.awt.Color(0,0,0,0));
        pnl_Background.setBackground(new java.awt.Color(0,0,0,0));
        
        this.product = product;
        
        txt_description.setText(product.getDescription());
        txt_costPrice.setText(product.getCostPrice().toString());
        txt_salePrice.setText(product.getSalePrice().toString());
        txt_quantity.setText(String.valueOf(product.getQuantity()));
        title.setText("Editar produto");
        Utils.updateComboBox(ColorDao.findAll(), cbColor);
        Utils.updateComboBox(CategoryDao.findAll(), cbCategory);
        
        setAllComboBoxRenderer();
        
        cbColor.setSelectedItem(product.getColor());
        cbCategory.setSelectedItem(product.getCategory());
        cbSize.setSelectedItem(product.getSize());
    }
    
    public void subscribeDataChangeListener(DataChangeListener listener) {
        listeners.add(listener);
    }
    
    private void notifyDataChangeListeners() {
        listeners.forEach(listener ->{
            listener.onDataChanged();
        });
    }
    
    private void setAllComboBoxRenderer() {
        for (Component c : pnl_Background.getComponents()) {
            if (c instanceof JComboBox) ((JComboBox)c).setRenderer(new ComboBoxRenderer());
        }
    }

    public JComboBox<Object> getCbCategory() {
        return cbCategory;
    }

    public JComboBox<Object> getCbColor() {
        return cbColor;
    }
    
    private Product instantiateProduct(Product p) {
        Double costPrice = Double.parseDouble(txt_costPrice.getText().replace(',', '.'));
        Double salePrice = Double.parseDouble(txt_salePrice.getText().replace(',', '.'));

        p.setDescription(txt_description.getText().toUpperCase());
        p.setCategory((Category) cbCategory.getSelectedItem());
        p.setColor((Color) cbColor.getSelectedItem());
        p.setQuantity(Integer.parseInt(txt_quantity.getText()));
        p.setCostPrice(costPrice);
        p.setSalePrice(salePrice);
        p.setSize(cbSize.getSelectedItem().toString());
        
        return p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Background = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_description = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbSize = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_salePrice = new javax.swing.JFormattedTextField();
        txt_costPrice = new javax.swing.JFormattedTextField();
        txt_quantity = new javax.swing.JFormattedTextField();
        bnt_save = new javax.swing.JLabel();
        btn_clear = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JLabel();
        cbColor = new javax.swing.JComboBox<>();
        cbCategory = new javax.swing.JComboBox<>();
        btn_addCategory = new javax.swing.JLabel();
        btn_addColor = new javax.swing.JLabel();
        btn_editCategory = new javax.swing.JLabel();
        btn_editColor = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        pnl_Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 51));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Cadastrar novo produto");
        pnl_Background.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 613, 40));

        jLabel8.setBackground(new java.awt.Color(59, 44, 150));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Descrição:");
        jLabel8.setOpaque(true);
        pnl_Background.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 110, 30));

        txt_description.setBackground(new java.awt.Color(0, 0, 51));
        txt_description.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_description.setForeground(new java.awt.Color(255, 255, 255));
        txt_description.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_description.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(108, 81, 233)));
        txt_description.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_description.setOpaque(false);
        pnl_Background.add(txt_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 400, 30));

        jLabel9.setBackground(new java.awt.Color(59, 44, 150));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cor:");
        jLabel9.setOpaque(true);
        pnl_Background.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 110, 30));

        jLabel6.setBackground(new java.awt.Color(59, 44, 150));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tamanho:");
        jLabel6.setOpaque(true);
        pnl_Background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 80, 30));

        cbSize.setBackground(new java.awt.Color(0, 0, 51));
        cbSize.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbSize.setForeground(new java.awt.Color(255, 255, 255));
        cbSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "PP", "P", "M", "G", "GG" }));
        pnl_Background.add(cbSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 80, 30));

        jLabel2.setBackground(new java.awt.Color(59, 44, 150));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Categoria:");
        jLabel2.setOpaque(true);
        pnl_Background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 110, 30));

        jLabel4.setBackground(new java.awt.Color(59, 44, 150));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("P. de custo:");
        jLabel4.setOpaque(true);
        pnl_Background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 110, 30));

        jLabel7.setBackground(new java.awt.Color(59, 44, 150));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("P. de venda:");
        jLabel7.setOpaque(true);
        pnl_Background.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 110, 30));

        jLabel5.setBackground(new java.awt.Color(59, 44, 150));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Qtd.:");
        jLabel5.setOpaque(true);
        pnl_Background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 50, 30));

        txt_salePrice.setBackground(new java.awt.Color(0, 0, 51));
        txt_salePrice.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(108, 81, 233)));
        txt_salePrice.setForeground(new java.awt.Color(255, 255, 255));
        txt_salePrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txt_salePrice.setOpaque(false);
        pnl_Background.add(txt_salePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 70, 30));

        txt_costPrice.setBackground(new java.awt.Color(0, 0, 51));
        txt_costPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(108, 81, 233)));
        txt_costPrice.setForeground(new java.awt.Color(255, 255, 255));
        txt_costPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txt_costPrice.setOpaque(false);
        pnl_Background.add(txt_costPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 70, 30));

        txt_quantity.setBackground(new java.awt.Color(0, 0, 51));
        txt_quantity.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(108, 81, 233)));
        txt_quantity.setForeground(new java.awt.Color(255, 255, 255));
        txt_quantity.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txt_quantity.setOpaque(false);
        pnl_Background.add(txt_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 60, 30));

        bnt_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_salvarClaro.png"))); // NOI18N
        bnt_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bnt_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_saveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bnt_saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bnt_saveMouseExited(evt);
            }
        });
        pnl_Background.add(bnt_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, 30));

        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_limparClaro.png"))); // NOI18N
        btn_clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_clearMouseExited(evt);
            }
        });
        pnl_Background.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_cancelarClaro.png"))); // NOI18N
        btn_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cancelMouseExited(evt);
            }
        });
        pnl_Background.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        cbColor.setBackground(new java.awt.Color(0, 0, 51));
        cbColor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbColor.setForeground(new java.awt.Color(255, 255, 255));
        pnl_Background.add(cbColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 160, 30));

        cbCategory.setBackground(new java.awt.Color(0, 0, 51));
        cbCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbCategory.setForeground(new java.awt.Color(255, 255, 255));
        cbCategory.setToolTipText("");
        pnl_Background.add(cbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 160, 30));

        btn_addCategory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_addCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_mais.png"))); // NOI18N
        btn_addCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_addCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addCategoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addCategoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addCategoryMouseExited(evt);
            }
        });
        pnl_Background.add(btn_addCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 30, 30));

        btn_addColor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_addColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_mais.png"))); // NOI18N
        btn_addColor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_addColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addColorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addColorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addColorMouseExited(evt);
            }
        });
        pnl_Background.add(btn_addColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 30, 30));

        btn_editCategory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_editCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit_19px.png"))); // NOI18N
        btn_editCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_editCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editCategoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editCategoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editCategoryMouseExited(evt);
            }
        });
        pnl_Background.add(btn_editCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 30, 30));

        btn_editColor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_editColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit_19px.png"))); // NOI18N
        btn_editColor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_editColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editColorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editColorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editColorMouseExited(evt);
            }
        });
        pnl_Background.add(btn_editColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 30, 30));

        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tela_cadastro_dark.png"))); // NOI18N
        pnl_Background.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, -1));

        getContentPane().add(pnl_Background, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bnt_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_saveMouseClicked
        //verificar se todos campos foram preenchidos
        
        if (Utils.isAllFieldsFilled(pnl_Background)) {
            
            if (product == null) {
                
                product = instantiateProduct(new Product());
                
                ProductDao.insert(product);
                JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso!",
                    "Atenção", JOptionPane.INFORMATION_MESSAGE);

                Utils.clearFields(pnl_Background);
                product = null;
            }
            else {
                instantiateProduct(product);
                ProductDao.update(product);
                JOptionPane.showMessageDialog(null, "Produto atualizado com sucesso!",
                    "Atenção", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
            notifyDataChangeListeners();
        }
        else {
            JOptionPane.showMessageDialog(null, "Você deve preencher todos os campos.",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_bnt_saveMouseClicked

    private void bnt_saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_saveMouseEntered
        // Trocar para ícone escuro
        bnt_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_salvar.png")));
    }//GEN-LAST:event_bnt_saveMouseEntered

    private void bnt_saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_saveMouseExited
        // Voltar para ícone original
        bnt_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_salvarClaro.png")));
    }//GEN-LAST:event_bnt_saveMouseExited

    private void btn_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseClicked
        // Limpar todos os campos (criar método depois)
        Utils.clearFields(pnl_Background);
    }//GEN-LAST:event_btn_clearMouseClicked

    private void btn_clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseEntered
        // Trocar para ícone escuro
        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_limpar.png")));
    }//GEN-LAST:event_btn_clearMouseEntered

    private void btn_clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseExited
        // Voltar para ícone original
        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_limparClaro.png")));
    }//GEN-LAST:event_btn_clearMouseExited

    private void btn_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_cancelMouseClicked

    private void btn_cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseEntered
        // Trocar para ícone escuro
        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_cancelar.png")));
    }//GEN-LAST:event_btn_cancelMouseEntered

    private void btn_cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseExited
        // Voltar para ícone original
        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_cancelarClaro.png")));
    }//GEN-LAST:event_btn_cancelMouseExited

    private void btn_addColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addColorMouseClicked
        // Chamar tela de cadastrar CORES
        new New_Color(this, true).setVisible(true);
    }//GEN-LAST:event_btn_addColorMouseClicked

    private void btn_addCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addCategoryMouseClicked
        // Chamar tela de cadastrar CATEGORIAS
        new New_Category(this, true).setVisible(true);
    }//GEN-LAST:event_btn_addCategoryMouseClicked

    private void btn_addColorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addColorMouseEntered
        btn_addColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_mais_claro.png")));
    }//GEN-LAST:event_btn_addColorMouseEntered

    private void btn_addColorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addColorMouseExited
        btn_addColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_mais.png")));
    }//GEN-LAST:event_btn_addColorMouseExited

    private void btn_addCategoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addCategoryMouseEntered
        btn_addCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_mais_claro.png")));
    }//GEN-LAST:event_btn_addCategoryMouseEntered

    private void btn_addCategoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addCategoryMouseExited
        btn_addCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_mais.png")));
    }//GEN-LAST:event_btn_addCategoryMouseExited

    private void btn_editColorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editColorMouseEntered
        btn_editColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit_19px_claro.png")));
    }//GEN-LAST:event_btn_editColorMouseEntered

    private void btn_editColorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editColorMouseExited
        btn_editColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit_19px.png")));
    }//GEN-LAST:event_btn_editColorMouseExited

    private void btn_editCategoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editCategoryMouseEntered
        btn_editCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit_19px_claro.png")));
    }//GEN-LAST:event_btn_editCategoryMouseEntered

    private void btn_editCategoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editCategoryMouseExited
        btn_editCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit_19px.png")));
    }//GEN-LAST:event_btn_editCategoryMouseExited

    private void btn_editColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editColorMouseClicked
        
        if (cbColor.getSelectedIndex() != 0) {
            Color c = (Color) cbColor.getSelectedItem();
            new Edit_Color(this, true, c).setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(null, "Você deve selecionar uma cor para poder editar.", 
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_editColorMouseClicked

    private void btn_editCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editCategoryMouseClicked
        if (cbCategory.getSelectedIndex() != 0) {
            Category c = (Category) cbCategory.getSelectedItem();
            new Edit_Category(this, true, c).setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(null, "Você deve selecionar uma categoria para poder editar.", 
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_editCategoryMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel bnt_save;
    private javax.swing.JLabel btn_addCategory;
    private javax.swing.JLabel btn_addColor;
    private javax.swing.JLabel btn_cancel;
    private javax.swing.JLabel btn_clear;
    private javax.swing.JLabel btn_editCategory;
    private javax.swing.JLabel btn_editColor;
    private javax.swing.JComboBox<Object> cbCategory;
    private javax.swing.JComboBox<Object> cbColor;
    private javax.swing.JComboBox<String> cbSize;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnl_Background;
    private javax.swing.JLabel title;
    private javax.swing.JFormattedTextField txt_costPrice;
    private javax.swing.JTextField txt_description;
    private javax.swing.JFormattedTextField txt_quantity;
    private javax.swing.JFormattedTextField txt_salePrice;
    // End of variables declaration//GEN-END:variables
}
