/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.sistemalojaroupas.view;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author lukas
 */
public class Register_New_Products extends javax.swing.JDialog {
    
    public void clearFields(JPanel pn){
        
        for (Component c : pn.getComponents()) {
            if (c instanceof JComboBox) ((JComboBox)c).setSelectedIndex(-1);
            if (c instanceof JTextField) ((JTextField)c).setText("");
        }
    } 
    /**
     * Creates new form Register_Products
     */
    
    Home home = new Home();
    
    public Register_New_Products(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();   
        this.setBackground(new Color(0,0,0,0));
        pnl_Background.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Background = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_description = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_color = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cb_size = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txt_category = new javax.swing.JTextField();
        txt_purchasePrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_salePrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_amount = new javax.swing.JTextField();
        bnt_save = new javax.swing.JLabel();
        btn_clear = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JLabel();
        btn_addCategory = new javax.swing.JLabel();
        btn_addColor = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        pnl_Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 0, 51));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Cadastrar novo produto");
        pnl_Background.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 613, 40));

        jLabel8.setBackground(new java.awt.Color(59, 44, 150));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Descrição:");
        jLabel8.setOpaque(true);
        pnl_Background.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 110, 30));

        txt_description.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_description.setForeground(new java.awt.Color(255, 255, 255));
        txt_description.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_description.setText("Camisa gola v");
        txt_description.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(108, 81, 233)));
        txt_description.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_description.setOpaque(false);
        pnl_Background.add(txt_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 400, 30));

        jLabel9.setBackground(new java.awt.Color(59, 44, 150));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cor:");
        jLabel9.setOpaque(true);
        pnl_Background.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 110, 30));

        txt_color.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_color.setForeground(new java.awt.Color(255, 255, 255));
        txt_color.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_color.setText("Vermelho escuro");
        txt_color.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(108, 81, 233)));
        txt_color.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_color.setOpaque(false);
        pnl_Background.add(txt_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 180, 30));

        jLabel6.setBackground(new java.awt.Color(59, 44, 150));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tamanho:");
        jLabel6.setOpaque(true);
        pnl_Background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 90, 30));

        cb_size.setBackground(new java.awt.Color(108, 81, 233));
        cb_size.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "PP", "P", "M", "G", "GG" }));
        pnl_Background.add(cb_size, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 70, 30));

        jLabel2.setBackground(new java.awt.Color(59, 44, 150));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Categoria:");
        jLabel2.setOpaque(true);
        pnl_Background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 110, 30));

        txt_category.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_category.setForeground(new java.awt.Color(255, 255, 255));
        txt_category.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_category.setText("Camisa");
        txt_category.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(108, 81, 233)));
        txt_category.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_category.setOpaque(false);
        pnl_Background.add(txt_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 180, 30));

        txt_purchasePrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_purchasePrice.setForeground(new java.awt.Color(255, 255, 255));
        txt_purchasePrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_purchasePrice.setText("100");
        txt_purchasePrice.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(108, 81, 233)));
        txt_purchasePrice.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_purchasePrice.setOpaque(false);
        pnl_Background.add(txt_purchasePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 70, 30));

        jLabel4.setBackground(new java.awt.Color(59, 44, 150));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("P. de custo:");
        jLabel4.setOpaque(true);
        pnl_Background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 110, 30));

        jLabel7.setBackground(new java.awt.Color(59, 44, 150));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("P. de venda:");
        jLabel7.setOpaque(true);
        pnl_Background.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 110, 30));

        txt_salePrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_salePrice.setForeground(new java.awt.Color(255, 255, 255));
        txt_salePrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_salePrice.setText("150");
        txt_salePrice.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(108, 81, 233)));
        txt_salePrice.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_salePrice.setOpaque(false);
        pnl_Background.add(txt_salePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 70, 30));

        jLabel5.setBackground(new java.awt.Color(59, 44, 150));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Qtd.:");
        jLabel5.setOpaque(true);
        pnl_Background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 50, 30));

        txt_amount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_amount.setForeground(new java.awt.Color(255, 255, 255));
        txt_amount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_amount.setText("5");
        txt_amount.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(108, 81, 233)));
        txt_amount.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_amount.setOpaque(false);
        pnl_Background.add(txt_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 60, 30));

        bnt_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_salvarClaro.png"))); // NOI18N
        bnt_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_saveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bnt_saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bnt_saveMouseExited(evt);
            }
        });
        pnl_Background.add(bnt_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_limparClaro.png"))); // NOI18N
        btn_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_clearMouseExited(evt);
            }
        });
        pnl_Background.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_cancelarClaro.png"))); // NOI18N
        btn_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cancelMouseExited(evt);
            }
        });
        pnl_Background.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        btn_addCategory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_addCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_mais.png"))); // NOI18N
        btn_addCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addCategoryMouseClicked(evt);
            }
        });
        pnl_Background.add(btn_addCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 30, 30));

        btn_addColor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_addColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_mais.png"))); // NOI18N
        btn_addColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addColorMouseClicked(evt);
            }
        });
        pnl_Background.add(btn_addColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 30, 30));

        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tela_cadastro_dark.png"))); // NOI18N
        pnl_Background.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, -1));

        getContentPane().add(pnl_Background, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bnt_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_saveMouseClicked
        //verificar se todos campos foram preenchidos
        
        //limpar todos os campos(criar método)
        txt_amount.setText(""); txt_category.setText(""); txt_color.setText(""); txt_description.setText(""); txt_purchasePrice.setText(""); txt_salePrice.setText("");
        // Mensagem de sucesso
        JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bnt_saveMouseClicked

    private void bnt_saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_saveMouseEntered
        // Trocar para ícone escuro
        bnt_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_salvar.png")));
    }//GEN-LAST:event_bnt_saveMouseEntered

    private void bnt_saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_saveMouseExited
        // Voltar para ícone original
        bnt_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_salvarClaro.png")));
    }//GEN-LAST:event_bnt_saveMouseExited

    private void btn_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseClicked
        // Limpar todos os campos (criar método depois)
        txt_amount.setText(""); txt_category.setText(""); txt_color.setText(""); txt_description.setText(""); txt_purchasePrice.setText(""); txt_salePrice.setText("");
        cb_size.setSelectedIndex(0);
    }//GEN-LAST:event_btn_clearMouseClicked

    private void btn_clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseEntered
        // Trocar para ícone escuro
        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_limpar.png")));
    }//GEN-LAST:event_btn_clearMouseEntered

    private void btn_clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseExited
        // Voltar para ícone original
        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_limparClaro.png")));
    }//GEN-LAST:event_btn_clearMouseExited

    private void btn_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_cancelMouseClicked

    private void btn_cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseEntered
        // Trocar para ícone escuro
        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_cancelar.png")));
    }//GEN-LAST:event_btn_cancelMouseEntered

    private void btn_cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseExited
        // Voltar para ícone original
        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_cancelarClaro.png")));
    }//GEN-LAST:event_btn_cancelMouseExited

    private void btn_addColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addColorMouseClicked
        // Chamar tela de cadastrar CORES
        new New_Color(home, true).setVisible(true);
    }//GEN-LAST:event_btn_addColorMouseClicked

    private void btn_addCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addCategoryMouseClicked
        // Chamar tela de cadastrar CATEGORIAS
        new New_Category(home, true).setVisible(true);
    }//GEN-LAST:event_btn_addCategoryMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_New_Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_New_Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_New_Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_New_Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Register_New_Products dialog = new Register_New_Products(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel bnt_save;
    private javax.swing.JLabel btn_addCategory;
    private javax.swing.JLabel btn_addColor;
    private javax.swing.JLabel btn_cancel;
    private javax.swing.JLabel btn_clear;
    private javax.swing.JComboBox<String> cb_size;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnl_Background;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_category;
    private javax.swing.JTextField txt_color;
    private javax.swing.JTextField txt_description;
    private javax.swing.JTextField txt_purchasePrice;
    private javax.swing.JTextField txt_salePrice;
    // End of variables declaration//GEN-END:variables
}
