/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.sistemalojaroupas.view.registration;

/**
 *
 * @author steuf0
 */
public class Change_Password extends javax.swing.JDialog {

    /**
     * Creates new form Change_Password
     */
    public Change_Password(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChangePassword = new javax.swing.JPanel();
        txtPasswordCurrent = new javax.swing.JTextField();
        PasswordCurrent = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ChangePwTitle = new javax.swing.JLabel();
        bnt_save = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JLabel();
        PasswordNew = new javax.swing.JLabel();
        txtPasswordNew = new javax.swing.JTextField();
        PasswordCheck = new javax.swing.JLabel();
        txtPasswordCheck = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ChangePassword.setBackground(new java.awt.Color(0, 0, 51));
        ChangePassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPasswordCurrent.setBackground(new java.awt.Color(0, 0, 0));
        txtPasswordCurrent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPasswordCurrent.setForeground(new java.awt.Color(255, 255, 255));
        txtPasswordCurrent.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(108, 81, 233)));
        txtPasswordCurrent.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPasswordCurrent.setOpaque(false);
        ChangePassword.add(txtPasswordCurrent, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 190, 30));

        PasswordCurrent.setBackground(new java.awt.Color(59, 44, 150));
        PasswordCurrent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PasswordCurrent.setForeground(new java.awt.Color(255, 255, 255));
        PasswordCurrent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordCurrent.setText("Senha atual:");
        PasswordCurrent.setOpaque(true);
        ChangePassword.add(PasswordCurrent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, 30));

        jPanel2.setBackground(new java.awt.Color(108, 81, 233));

        ChangePwTitle.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ChangePwTitle.setForeground(new java.awt.Color(0, 0, 51));
        ChangePwTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChangePwTitle.setText("Alterar senha");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(ChangePwTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ChangePwTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        ChangePassword.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        bnt_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_salvarClaro.png"))); // NOI18N
        bnt_save.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bnt_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_saveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bnt_saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bnt_saveMouseExited(evt);
            }
        });
        ChangePassword.add(bnt_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, 30));

        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_cancelarClaro.png"))); // NOI18N
        btn_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cancelMouseExited(evt);
            }
        });
        ChangePassword.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        PasswordNew.setBackground(new java.awt.Color(59, 44, 150));
        PasswordNew.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PasswordNew.setForeground(new java.awt.Color(255, 255, 255));
        PasswordNew.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordNew.setText("Nova senha:");
        PasswordNew.setOpaque(true);
        ChangePassword.add(PasswordNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, 30));

        txtPasswordNew.setBackground(new java.awt.Color(0, 0, 0));
        txtPasswordNew.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPasswordNew.setForeground(new java.awt.Color(255, 255, 255));
        txtPasswordNew.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(108, 81, 233)));
        txtPasswordNew.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPasswordNew.setOpaque(false);
        ChangePassword.add(txtPasswordNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 190, 30));

        PasswordCheck.setBackground(new java.awt.Color(59, 44, 150));
        PasswordCheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PasswordCheck.setForeground(new java.awt.Color(255, 255, 255));
        PasswordCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordCheck.setText("Repita a senha:");
        PasswordCheck.setOpaque(true);
        ChangePassword.add(PasswordCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 120, 30));

        txtPasswordCheck.setBackground(new java.awt.Color(0, 0, 0));
        txtPasswordCheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPasswordCheck.setForeground(new java.awt.Color(255, 255, 255));
        txtPasswordCheck.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(108, 81, 233)));
        txtPasswordCheck.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPasswordCheck.setOpaque(false);
        txtPasswordCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordCheckActionPerformed(evt);
            }
        });
        ChangePassword.add(txtPasswordCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnt_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_saveMouseClicked
        
        
    }//GEN-LAST:event_bnt_saveMouseClicked

    private void bnt_saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_saveMouseEntered
        // Trocar para ícone escuro
        bnt_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_salvar.png")));
    }//GEN-LAST:event_bnt_saveMouseEntered

    private void bnt_saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_saveMouseExited
        // Voltar para ícone original
        bnt_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_salvarClaro.png")));
    }//GEN-LAST:event_bnt_saveMouseExited

    private void btn_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_cancelMouseClicked

    private void btn_cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseEntered
        // Trocar para ícone escuro
        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_cancelar.png")));
    }//GEN-LAST:event_btn_cancelMouseEntered

    private void btn_cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseExited
        // Voltar para ícone original
        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_cancelarClaro.png")));
    }//GEN-LAST:event_btn_cancelMouseExited

    private void txtPasswordCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Change_Password dialog = new Change_Password(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChangePassword;
    private javax.swing.JLabel ChangePwTitle;
    private javax.swing.JLabel PasswordCheck;
    private javax.swing.JLabel PasswordCurrent;
    private javax.swing.JLabel PasswordNew;
    private javax.swing.JLabel bnt_save;
    private javax.swing.JLabel btn_cancel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtPasswordCheck;
    private javax.swing.JTextField txtPasswordCurrent;
    private javax.swing.JTextField txtPasswordNew;
    // End of variables declaration//GEN-END:variables
}
